// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type BackupOperation struct {
	ID         int64        `json:"id"`
	StartedAt  time.Time    `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
	Operation  string       `json:"operation"`
	Parameters string       `json:"parameters"`
	Status     string       `json:"status"`
}

type Content struct {
	ID                 string         `json:"id"`
	CreatedAt          time.Time      `json:"created_at"`
	EncryptedContentID sql.NullString `json:"encrypted_content_id"`
}

type Directory struct {
	ID        string    `json:"id"`
	Path      string    `json:"path"`
	CreatedAt time.Time `json:"created_at"`
	Encrypted int64     `json:"encrypted"`
}

type File struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	DirectoryID       string         `json:"directory_id"`
	CurrentSnapshotID sql.NullString `json:"current_snapshot_id"`
	Deleted           bool           `json:"deleted"`
}

type FileSnapshot struct {
	ID          string       `json:"id"`
	FileID      string       `json:"file_id"`
	ContentID   string       `json:"content_id"`
	CreatedAt   time.Time    `json:"created_at"`
	Size        int64        `json:"size"`
	Permissions int64        `json:"permissions"`
	Uid         int64        `json:"uid"`
	Gid         int64        `json:"gid"`
	AccessedAt  time.Time    `json:"accessed_at"`
	ModifiedAt  time.Time    `json:"modified_at"`
	ChangedAt   time.Time    `json:"changed_at"`
	BornAt      sql.NullTime `json:"born_at"`
}
