// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteDirectoryByID(ctx context.Context, id string) error
	GetDirectoriesByPathPrefix(ctx context.Context, path string) ([]Directory, error)
	// SQL queries for bt database operations
	// sqlc will generate type-safe Go code from these queries
	// See: https://docs.sqlc.dev/en/latest/
	// Directory queries
	GetDirectoryByPath(ctx context.Context, path string) (Directory, error)
	// File queries
	GetFilesByDirectoryID(ctx context.Context, directoryID string) ([]File, error)
	InsertDirectory(ctx context.Context, arg InsertDirectoryParams) (Directory, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
	UpdateFileDirectoryAndName(ctx context.Context, arg UpdateFileDirectoryAndNameParams) error
}

var _ Querier = (*Queries)(nil)
