// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateDirectory(ctx context.Context, arg CreateDirectoryParams) (Directory, error)
	// SQL queries for bt database operations
	// sqlc will generate type-safe Go code from these queries
	// See: https://docs.sqlc.dev/en/latest/
	// Directory queries
	GetDirectory(ctx context.Context, id string) (Directory, error)
	ListDirectories(ctx context.Context) ([]Directory, error)
}

var _ Querier = (*Queries)(nil)
