// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"time"
)

const createDirectory = `-- name: CreateDirectory :one
INSERT INTO directories (id, path, created_at)
VALUES (?, ?, ?)
RETURNING id, path, created_at
`

type CreateDirectoryParams struct {
	ID        string    `json:"id"`
	Path      string    `json:"path"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateDirectory(ctx context.Context, arg CreateDirectoryParams) (Directory, error) {
	row := q.db.QueryRowContext(ctx, createDirectory, arg.ID, arg.Path, arg.CreatedAt)
	var i Directory
	err := row.Scan(&i.ID, &i.Path, &i.CreatedAt)
	return i, err
}

const getDirectory = `-- name: GetDirectory :one


SELECT id, path, created_at FROM directories WHERE id = ? LIMIT 1
`

// SQL queries for bt database operations
// sqlc will generate type-safe Go code from these queries
// See: https://docs.sqlc.dev/en/latest/
// Directory queries
func (q *Queries) GetDirectory(ctx context.Context, id string) (Directory, error) {
	row := q.db.QueryRowContext(ctx, getDirectory, id)
	var i Directory
	err := row.Scan(&i.ID, &i.Path, &i.CreatedAt)
	return i, err
}

const listDirectories = `-- name: ListDirectories :many
SELECT id, path, created_at FROM directories ORDER BY path
`

func (q *Queries) ListDirectories(ctx context.Context) ([]Directory, error) {
	rows, err := q.db.QueryContext(ctx, listDirectories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Directory
	for rows.Next() {
		var i Directory
		if err := rows.Scan(&i.ID, &i.Path, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
